---
- name: Adyen
  grade: B
  url: https://github.com/Adyen/adyen-openapi
- name: Amazon Partners
  grade: B
  url: https://github.com/amzn/selling-partner-api-models
- name: Azure
  grade: B
  url: https://github.com/Azure/azure-rest-api-specs
- name: BigCommerce
  grade: B
  url: https://github.com/bigcommerce/docs
- name: Box
  grade: B
  url: https://github.com/box/box-openapi
- name: CloudFlare
  grade: C
  url: https://github.com/cloudflare/api-schemas
- name: Digital Ocean
  grade: A
  url: https://github.com/digitalocean/openapi
- name: Discord
  grade: B
  url: https://github.com/discord/discord-api-spec
- name: GitHub
  grade: B
  url: https://github.com/github/rest-api-description
- name: New York Times
  grade: C
  url: https://github.com/nytimes/public_api_specs
- name: OpenAI
  grade: C
  url: https://github.com/openai/openai-openapi
- name: Plaid
  grade: C
  url: https://github.com/plaid/plaid-openapi
- name: Stripe
  grade: B
  url: https://github.com/stripe/openapi
- name: Twilio
  grade: B
  url: https://github.com/twilio/twilio-oai